import type { CronForm, CronTask, Locale, Server } from "../../domain/types";

export function CronPanel({ tasks, servers, selectedServerId, loading, editorOpen, form, language, error, onServerChange, onRefresh, onNew, onEdit, onToggle, onDelete, onFormChange, onSave, onCloseEditor, onExit }: { tasks: CronTask[]; servers: Server[]; selectedServerId: string; loading: boolean; editorOpen: boolean; form: CronForm; language: Locale; error: string; onServerChange: (id: string) => void; onRefresh: () => void; onNew: () => void; onEdit: (task: CronTask) => void; onToggle: (task: CronTask) => void; onDelete: (task: CronTask) => void; onFormChange: (form: CronForm) => void; onSave: () => void; onCloseEditor: () => void; onExit: () => void }) {
  const zhMode = language === "zh-CN";
  return <section className="cron-view">
    <header className="cron-header"><div><p className="eyebrow">OpsNest</p><h1>{zhMode ? "定时任务" : "Scheduled tasks"}</h1><span>{zhMode ? "任务运行在服务器自身，OpsNest 只负责读取和管理。" : "Tasks run on each server. OpsNest only reads and manages them."}</span></div><button className="secondary" onClick={onExit}>{zhMode ? "返回服务器" : "Back to servers"}</button></header>
    {!servers.length ? <div className="cron-empty"><h2>{zhMode ? "还没有服务器" : "No servers yet"}</h2><p>{zhMode ? "先添加一台服务器，再查看它的 Cron 和 systemd timer。" : "Add a server first to inspect its Cron jobs and systemd timers."}</p></div> : <>
      <div className="cron-toolbar"><label>{zhMode ? "目标服务器" : "Target server"}<select value={selectedServerId} onChange={(event) => onServerChange(event.target.value)}>{servers.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.host}</option>)}</select></label><div><button className="secondary" onClick={onRefresh} disabled={loading}>{loading ? (zhMode ? "读取中…" : "Loading…") : (zhMode ? "刷新" : "Refresh")}</button><button className="primary" onClick={onNew}>{zhMode ? "＋ 添加服务器任务" : "＋ Add server task"}</button></div></div>
      {error && <div className="global-error">{error}</div>}
      <div className="cron-note"><span>◉</span><div><strong>{zhMode ? "服务器端执行" : "Runs on the server"}</strong><p>{zhMode ? "保存后会写入目标服务器当前用户的 crontab；OpsNest 关闭后，服务器仍会按原计划执行。" : "Saved jobs are written to the target user's crontab. They keep running after OpsNest closes."}</p></div></div>
      <div className="cron-list">{loading && !tasks.length ? <div className="cron-empty"><p>{zhMode ? "正在读取服务器上的 Cron 和 systemd timer…" : "Reading Cron jobs and systemd timers from the server…"}</p></div> : tasks.length ? tasks.map((task) => <article className={`cron-card ${task.enabled ? "enabled" : "disabled"}`} key={task.id}><div className="cron-card-main"><div className="cron-card-title"><span className={`cron-status-dot ${task.enabled ? "on" : "off"}`}></span><div><h2>{task.name}</h2><small>{task.source} · {task.user}</small></div></div><code>{task.schedule} {task.command}</code><p>{task.detail}</p></div><div className="cron-card-actions">{task.editable ? <><button className="text-button" onClick={() => onToggle(task)}>{task.enabled ? (zhMode ? "停用" : "Disable") : (zhMode ? "启用" : "Enable")}</button><button className="text-button" onClick={() => onEdit(task)}>{zhMode ? "编辑" : "Edit"}</button><button className="text-button danger-text" onClick={() => { if (window.confirm(zhMode ? "删除这条服务器 Cron 任务？" : "Delete this server Cron task?")) onDelete(task); }}>{zhMode ? "删除" : "Delete"}</button></> : <span className="read-only-pill">{zhMode ? "只读" : "Read only"}</span>}</div></article>) : <div className="cron-empty"><div>⌁</div><h2>{zhMode ? "没有读取到定时任务" : "No scheduled tasks found"}</h2><p>{zhMode ? "可以添加第一条服务器任务。" : "Add the first server-side task."}</p></div>}</div>
    </>}
    {editorOpen && <div className="modal-backdrop" role="presentation"><section className="wizard cron-editor" role="dialog" aria-modal="true"><div className="wizard-header"><div><p className="eyebrow">{zhMode ? "服务器 Cron" : "Server Cron"}</p><h2>{zhMode ? "添加定时任务" : "Add scheduled task"}</h2></div><button className="close-button" onClick={onCloseEditor}>×</button></div><p className="wizard-intro">{zhMode ? "这条任务会写入目标服务器当前用户的 crontab。" : "This task will be written to the target server user's crontab."}</p><label>{zhMode ? "任务名称" : "Task name"}<input value={form.name} onChange={(event) => onFormChange({ ...form, name: event.target.value })} placeholder={zhMode ? "例如：每日备份" : "For example: Daily backup"} /></label><label>{zhMode ? "Cron 表达式" : "Cron expression"}<input value={form.schedule} onChange={(event) => onFormChange({ ...form, schedule: event.target.value })} placeholder="0 3 * * *" /></label><label>{zhMode ? "执行命令" : "Command"}<textarea rows={4} value={form.command} onChange={(event) => onFormChange({ ...form, command: event.target.value })} placeholder={zhMode ? "例如：/usr/local/bin/backup.sh" : "For example: /usr/local/bin/backup.sh"} /></label><label className="cron-enabled-field"><input type="checkbox" checked={form.enabled} onChange={(event) => onFormChange({ ...form, enabled: event.target.checked })} /> {zhMode ? "立即启用" : "Enable now"}</label><div className="wizard-footer"><button className="secondary" onClick={onCloseEditor}>{zhMode ? "取消" : "Cancel"}</button><button className="primary" onClick={onSave} disabled={loading}>{loading ? (zhMode ? "保存中…" : "Saving…") : (zhMode ? "保存到服务器" : "Save to server")}</button></div></section></div>}
  </section>;
}
