import { DockerContainersPanel } from "../docker/containers-panel";
import { ServiceIcon, setActiveServiceIconServer } from "../icons/services";
import { CustomServiceCard } from "../services/custom-shortcuts";
import { getServiceUrl, openServiceUrl } from "../services/url";
import { ServerDetailHeader } from "./detail-chrome";
import type { ServerDetailProps } from "./detail-contract";
import { displayRouterValue, getDockerService, getRouterServiceStatusLabel } from "./detail-helpers";
import { buildRouterOverviewFooter } from "./detail-metrics";

export function OpenWrtRouterDetailView({ server, text, language, onBack, onOpen, onConnect, onScan, isScanning, onDiscover, isDiscovering, onManager, onAddCustomService }: ServerDetailProps) {
  setActiveServiceIconServer(server.id);
  const zhMode = language === "zh-CN";
  const profile = server.profile;
  const router = profile?.openwrt;
  const connected = server.status === "connected";
  const allServices = server.services ?? [];
  const dockerService = getDockerService(allServices);
  const dockerInstalled = Boolean(profile?.dockerInstalled || dockerService);
  const services = [...allServices.filter((service) => service.id.toLowerCase() !== "docker" && service.web && service.port), ...(server.customServices ?? [])];
  const visibleServices = services.filter((service) => !service.id.startsWith("custom-"));
  const statusLabel = (status: string) => getRouterServiceStatusLabel(status, zhMode);
  const overviewFooter = buildRouterOverviewFooter(server, profile, zhMode);

  return <section className="server-detail-view router-detail-view">
    <ServerDetailHeader server={server} text={text} language={language} eyebrow={zhMode ? "OpenWrt 路由器" : "OpenWrt router"} onBack={onBack} router />
    <section className="router-overview-card"><div className="router-overview-heading"><div><p className="eyebrow">OpenWrt</p><h2>{displayRouterValue(router?.model, profile?.osName ?? "OpenWrt")}</h2><span>{displayRouterValue(router?.firmware, profile?.osVersion || (zhMode ? "固件信息将在连接后读取" : "Firmware information is read after connection"))}</span></div><div className="router-kernel-pill"><small>{zhMode ? "内核分支" : "Kernel branch"}</small><strong>{displayRouterValue(router?.kernel, profile?.osVersion || "—")}</strong></div></div><div className="router-metric-grid"><div className="router-metric-wan"><span>{zhMode ? "外网 WAN" : "WAN / Internet"}</span><strong>{displayRouterValue(router?.wanIp, "—")}</strong><small>{zhMode ? "当前出口地址" : "Current uplink address"}</small></div><div className="router-metric-lan"><span>{zhMode ? "内网 LAN" : "LAN network"}</span><strong>{displayRouterValue(router?.lanIp, "—")}</strong><small>{zhMode ? "路由器内网地址" : "Router LAN address"}</small></div><div><span>{zhMode ? "内网客户端" : "LAN clients"}</span><strong>{displayRouterValue(router?.lanClients, "0")}</strong><small>{zhMode ? "在线邻居 / DHCP 客户端" : "Reachable and DHCP clients"}</small></div><div><span>{zhMode ? "无线客户端" : "Wi-Fi clients"}</span><strong>{displayRouterValue(router?.wifiClients, "0")}</strong><small>{zhMode ? "无线接口已关联设备" : "Associated wireless stations"}</small></div></div><div className="router-overview-footer"><span>{overviewFooter}</span><button className="text-button" onClick={onScan} disabled={!connected || isScanning}>{isScanning ? (zhMode ? "扫描中…" : "Scanning…") : (zhMode ? "重新扫描" : "Rescan router")}</button></div></section>
    {dockerInstalled && <section className="docker-overview-card"><div className="docker-card-heading"><div className="docker-brand"><ServiceIcon service={{ id: "docker", category: "container" }} large /><div><p className="eyebrow">Docker</p><h2>{zhMode ? "容器运行概览" : "Container overview"}</h2><span>{zhMode ? "查看 Docker 安装状态、版本和正在运行的容器。" : "Docker status, version and running containers."}</span></div></div><span className="connected-badge connected-badge">● {dockerService?.status === "running" ? (zhMode ? "运行中" : "Running") : (zhMode ? "已安装" : "Installed")}</span></div><div className="docker-card-stats"><div><span>{zhMode ? "运行中容器" : "Running containers"}</span><strong>{profile?.dockerContainers ?? "—"}</strong></div><div><span>{zhMode ? "Docker 版本" : "Docker version"}</span><strong>{dockerService?.version || (zhMode ? "已安装" : "Installed")}</strong></div><div><span>{zhMode ? "管理方式" : "Management"}</span><strong>SSH</strong></div><div><span>{zhMode ? "数据来源" : "Source"}</span><strong>{zhMode ? "服务器扫描" : "Server scan"}</strong></div></div><DockerContainersPanel server={server} containers={profile?.dockerItems ?? []} language={language} onRefresh={onScan} refreshing={isScanning} /></section>}
    <section className="detail-section router-services-section"><div className="detail-section-heading"><div><p className="eyebrow">{zhMode ? "路由器服务" : "Router services"}</p><h2>{zhMode ? "内置服务与管理入口" : "Built-in services and entry points"}</h2></div><button className="text-button" onClick={onDiscover} disabled={!connected || isDiscovering}>{isDiscovering ? (zhMode ? "发现中…" : "Discovering…") : (zhMode ? "重新发现" : "Discover again")}</button></div>{visibleServices.length ? <div className="router-service-grid">{visibleServices.map((service) => { const url = getServiceUrl(server.host, service); return <article className={`router-service-card ${service.status === "running" ? "router-service-running" : ""}`} key={service.id}><div className="router-service-card-top"><ServiceIcon service={service} serverId={server.id} large /><span className="router-service-status">● {statusLabel(service.status)}</span></div><h3>{service.name}</h3><p>{service.version || (zhMode ? "OpenWrt 内置组件" : "OpenWrt component")}</p><small>{service.port ? `${zhMode ? "端口" : "Port"} :${service.port}` : (zhMode ? "系统服务" : "System service")}</small><button className="service-entry-button" onClick={() => openServiceUrl(url)}>{zhMode ? "打开管理页" : "Open panel"}</button></article>; })}<CustomServiceCard serverId={server.id} language={language} onAdd={onAddCustomService} /></div> : <><div className="service-discovery-empty"><strong>{zhMode ? "尚未读取路由器服务" : "Router services have not been scanned"}</strong><span>{zhMode ? "连接后点击重新发现，OpsNest 会读取 OpenWrt 的内置服务和常见插件。" : "Connect and run discovery to read built-in OpenWrt services and common plugins."}</span><button className="secondary" onClick={onDiscover} disabled={!connected || isDiscovering}>{isDiscovering ? (zhMode ? "发现中…" : "Discovering…") : (zhMode ? "立即发现" : "Discover now")}</button></div><CustomServiceCard serverId={server.id} language={language} onAdd={onAddCustomService} /></>}</section>
    <div className="router-bottom-grid"><button className="quick-action" onClick={onOpen}><span>〉</span><div><strong>{zhMode ? "原生 SSH 终端" : "Native SSH terminal"}</strong><small>{zhMode ? "进入路由器命令行" : "Open the router shell"}</small></div></button><button className="quick-action" onClick={onManager}><span>✦</span><div><strong>{zhMode ? "让 AI 管理路由器" : "Ask AI to manage the router"}</strong><small>{zhMode ? "分析网络和内置服务" : "Analyze network and built-in services"}</small></div></button></div>
  </section>;
}
