import { useState } from "react";
import type { ActivityLog, ConversationLog, Locale, RuntimeLog } from "../../domain/types";

export function TaskHistoryPanel({ logs, runtimeLogs, conversationLogs, language, onClear, onClearRuntime, onClearConversations, onExit }: { logs: ActivityLog[]; runtimeLogs: RuntimeLog[]; conversationLogs: ConversationLog[]; language: Locale; onClear: () => void; onClearRuntime: () => void; onClearConversations: () => void; onExit: () => void }) {
  const [tab, setTab] = useState<"activity" | "runtime" | "conversation">("activity");
  const label = language === "zh-CN" ? { title: "日志与任务", subtitle: "分开查看操作记录、软件运行日志和 AI 对话", empty: "还没有日志记录", clear: "清空当前记录", exit: "返回服务器", activity: "任务记录", runtime: "软件运行日志", conversation: "AI 对话日志", manager: "服务器总管", terminal: "SSH 终端", agent: "AgentRun", system: "系统", info: "信息", warn: "警告", error: "错误" } : { title: "Logs and activity", subtitle: "Review actions, runtime diagnostics and AI conversations separately", empty: "No logs recorded yet", clear: "Clear current log", exit: "Back to servers", activity: "Activity", runtime: "Runtime logs", conversation: "AI conversations", manager: "Server manager", terminal: "SSH terminal", agent: "AgentRun", system: "System", info: "Info", warn: "Warning", error: "Error" };
  const typeLabel = (type: ActivityLog["type"]) => label[type];
  const clearCurrent = tab === "activity" ? onClear : tab === "runtime" ? onClearRuntime : onClearConversations;
  const renderEmpty = () => <div className="task-history-empty"><div>⌁</div><h2>{label.empty}</h2></div>;
  return <section className="task-history-view"><header className="task-history-header"><div><p className="eyebrow">OpsNest</p><h1>{label.title}</h1><span>{label.subtitle}</span></div><div className="task-history-actions"><button className="secondary" onClick={clearCurrent}>{label.clear}</button><button className="primary" onClick={onExit}>{label.exit}</button></div></header><div className="task-history-tabs"><button className={tab === "activity" ? "active" : ""} onClick={() => setTab("activity")}>{label.activity} <b>{logs.length}</b></button><button className={tab === "runtime" ? "active" : ""} onClick={() => setTab("runtime")}>{label.runtime} <b>{runtimeLogs.length}</b></button><button className={tab === "conversation" ? "active" : ""} onClick={() => setTab("conversation")}>{label.conversation} <b>{conversationLogs.length}</b></button></div>{tab === "activity" && (logs.length ? <div className="task-history-list">{[...logs].reverse().map((log) => <article className={`task-log-card ${log.status ?? "info"}`} key={log.id}><div className="task-log-top"><strong>{typeLabel(log.type)} · {log.title}</strong><time>{new Date(log.timestamp).toLocaleString(language === "zh-CN" ? "zh-CN" : "en-US")}</time></div>{log.serverName && <small>{log.serverName}</small>}<pre>{log.content}</pre></article>)}</div> : renderEmpty())}{tab === "runtime" && (runtimeLogs.length ? <div className="task-history-list">{[...runtimeLogs].reverse().map((log) => <article className={`task-log-card ${log.level === "error" ? "failed" : log.level === "warn" ? "cancelled" : "info"}`} key={log.id}><div className="task-log-top"><strong>{log.level === "error" ? label.error : log.level === "warn" ? label.warn : label.info} · {log.event}</strong><time>{new Date(log.timestamp).toLocaleString(language === "zh-CN" ? "zh-CN" : "en-US")}</time></div><pre>{log.details ? `${log.message}\n\n${log.details}` : log.message}</pre></article>)}</div> : renderEmpty())}{tab === "conversation" && (conversationLogs.length ? <div className="task-history-list">{[...conversationLogs].reverse().map((log) => <article className="task-log-card" key={log.id}><div className="task-log-top"><strong>{log.scope === "manager" ? label.manager : label.terminal} · {log.role}</strong><time>{new Date(log.timestamp).toLocaleString(language === "zh-CN" ? "zh-CN" : "en-US")}</time></div>{log.serverName && <small>{log.serverName}</small>}<pre>{log.content}</pre></article>)}</div> : renderEmpty())}</section>;
}
